import { describe, it, expect } from 'vitest';
import { p256 } from '@noble/curves/p256';
import { hexToBytes, decodeAbiParameters } from 'viem';
import { extractXY, parseDerSignature, webauthnIndices, encodeWebAuthnSignature } from './webauthn';

/**
 * LOCKED WebAuthn (P-256) vector — the SAME one hardcoded on-chain in
 * contracts/test/fixtures/WebAuthnVector.sol. Generated by scripts/gen-webauthn-vector.mjs.
 * Any change to the signature format/derivation breaks both this file and the Solidity tests.
 * Regenerate with `npm run gen:vector`.
 */
const VECTOR = {
  privateKey: '0xc9afa9d845ba75166b5c215767b1d6934e50c3db36e89b127b8a622b120f6721',
  pubKeyX: '0x60fed4ba255a9d31c961eb74c6356d68c049b8923b61fa6ce669622e60f29fb6',
  pubKeyY: '0x7903fe1008b8bc99a41ae9e95628bc64f2f1b20c2d7e9f5177a3c294d4462299',
  userOpHash: '0x0a3e26d20c77ce020cc294bb50f3144fd3d85b4cf1f3578f45ba9a1067c6ff26',
  r: '0x355556da782fe9055335e0bfd6dbb648ea8a41fb9f2dd49eb34e30205a271b13',
  s: '0x4ae9f621ec076527f4daa5a447da8f6c727aea134e187820d69f7db7278f9711',
  challengeIndex: 23,
  typeIndex: 1,
  authenticatorData: '0xe03670c58143d03af056aab89fcb3e896846b3dc67e5a17a7bc2bf11029166170500000000',
  clientDataJSON:
    '{"type":"webauthn.get","challenge":"Cj4m0gx3zgIMwpS7UPMUT9PYW0zx81ePRbqaEGfG_yY","origin":"https://erc4337.onrender.com","crossOrigin":false}',
  uncompressedPoint:
    '0x0460fed4ba255a9d31c961eb74c6356d68c049b8923b61fa6ce669622e60f29fb67903fe1008b8bc99a41ae9e95628bc64f2f1b20c2d7e9f5177a3c294d4462299',
} as const;

describe('webauthn — public key extraction', () => {
  it('extracts (x, y) from the trailing 65 bytes of the SPKI/point', () => {
    const { x, y } = extractXY(hexToBytes(VECTOR.uncompressedPoint));
    expect(x).toBe(VECTOR.pubKeyX);
    expect(y).toBe(VECTOR.pubKeyY);
  });

  it('also works when the point is prefixed (SPKI wrapper simulated)', () => {
    const wrapped = hexToBytes(('0xdeadbeef' + VECTOR.uncompressedPoint.slice(2)) as `0x${string}`);
    const { x, y } = extractXY(wrapped);
    expect(x).toBe(VECTOR.pubKeyX);
    expect(y).toBe(VECTOR.pubKeyY);
  });
});

describe('webauthn — DER signature parsing', () => {
  it('parses a low-s DER signature into (r, s)', () => {
    const der = p256.Signature.fromCompact(VECTOR.r.slice(2) + VECTOR.s.slice(2)).toDERRawBytes();
    expect(parseDerSignature(der)).toEqual({ r: VECTOR.r, s: VECTOR.s });
  });

  it('normalizes a HIGH-s signature back to low-s (malleability guard)', () => {
    const highS = p256.CURVE.n - BigInt(VECTOR.s);
    const der = p256.Signature
      .fromCompact(VECTOR.r.slice(2) + highS.toString(16).padStart(64, '0'))
      .toDERRawBytes();
    // Same (r, s) as the low-s vector: parseDerSignature must have flipped s.
    expect(parseDerSignature(der)).toEqual({ r: VECTOR.r, s: VECTOR.s });
  });
});

describe('webauthn — clientDataJSON indices', () => {
  it('finds the challenge and type field offsets', () => {
    expect(webauthnIndices(VECTOR.clientDataJSON)).toEqual({
      challengeIndex: VECTOR.challengeIndex,
      typeIndex: VECTOR.typeIndex,
    });
  });
});

describe('webauthn — signature encoding', () => {
  const params = [
    { type: 'bytes32' },
    { type: 'bytes32' },
    { type: 'uint256' },
    { type: 'uint256' },
    { type: 'bytes' },
    { type: 'string' },
  ] as const;

  const encoded = encodeWebAuthnSignature({
    r: VECTOR.r,
    s: VECTOR.s,
    challengeIndex: VECTOR.challengeIndex,
    typeIndex: VECTOR.typeIndex,
    authenticatorData: VECTOR.authenticatorData,
    clientDataJSON: VECTOR.clientDataJSON,
  });

  it('is a TOP-LEVEL tuple: the first word is r, NOT a 0x20 offset (the tryDecodeAuth trap)', () => {
    expect(encoded.slice(0, 66)).toBe(VECTOR.r);
  });

  it('round-trips through decodeAbiParameters with the same fields', () => {
    const [r, s, challengeIndex, typeIndex, authenticatorData, clientDataJSON] = decodeAbiParameters(
      params,
      encoded,
    );
    expect(r).toBe(VECTOR.r);
    expect(s).toBe(VECTOR.s);
    expect(challengeIndex).toBe(BigInt(VECTOR.challengeIndex));
    expect(typeIndex).toBe(BigInt(VECTOR.typeIndex));
    expect(authenticatorData).toBe(VECTOR.authenticatorData);
    expect(clientDataJSON).toBe(VECTOR.clientDataJSON);
  });
});
